#!/usr/bin/env node
/**
 * Converts animations.txt (hex strings) to C++ header file
 * for use in microcontroller firmware
 *
 * Input: seeduino_xiao/animations.txt
 * Output: seeduino_xiao/src/animations.h
 */

import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

const INPUT_FILE = join(process.cwd(), 'seeduino_xiao', 'animations.txt')
const OUTPUT_FILE = join(process.cwd(), 'seeduino_xiao', 'src', 'animations.h')

type ParsedAnimation = {
  palette: number[] // 24 bytes (8 colors × 3 bytes RGB)
  frames: number[] // 512 bytes (8 frames × 64 pixels)
}

/**
 * Parses a hex string into palette and frames
 */
function parseHexString(hex: string, lineNum: number): ParsedAnimation {
  // Remove whitespace
  hex = hex.trim()

  // Validate length
  if (hex.length !== 560) {
    throw new Error(
      `Line ${lineNum}: Invalid hex length ${hex.length}, expected 560 characters`
    )
  }

  // Validate hex format
  if (!/^[0-9a-fA-F]+$/.test(hex)) {
    throw new Error(`Line ${lineNum}: Invalid hex characters`)
  }

  // Parse palette (48 hex chars = 24 bytes)
  const palette: number[] = []
  for (let i = 0; i < 48; i += 2) {
    palette.push(parseInt(hex.slice(i, i + 2), 16))
  }

  // Parse frames (512 hex chars = 512 nibbles = 512 bytes)
  const frames: number[] = []
  for (let i = 48; i < 560; i++) {
    frames.push(parseInt(hex[i], 16))
  }

  return { palette, frames }
}

/**
 * Generates C++ array initialization string
 */
function generateByteArray(bytes: number[]): string {
  return bytes.map((b) => `0x${b.toString(16).padStart(2, '0')}`).join(', ')
}

/**
 * Main function
 */
function main() {
  console.log('Converting animations.txt to C++ header...')
  console.log(`Input:  ${INPUT_FILE}`)
  console.log(`Output: ${OUTPUT_FILE}`)

  // Read input file
  let content: string
  try {
    content = readFileSync(INPUT_FILE, 'utf-8')
  } catch (error) {
    console.error(`Error reading ${INPUT_FILE}:`, error)
    process.exit(1)
  }

  // Parse lines
  const lines = content.split('\n')
  const animations: ParsedAnimation[] = []

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim()

    // Skip empty lines and comments
    if (!line || line.startsWith('#')) {
      continue
    }

    try {
      const animation = parseHexString(line, i + 1)
      animations.push(animation)
    } catch (error) {
      console.error(`Error:`, error)
      process.exit(1)
    }
  }

  if (animations.length === 0) {
    console.error('Error: No animations found in animations.txt')
    process.exit(1)
  }

  console.log(`Found ${animations.length} animation(s)`)

  // Generate C++ header
  const header = `// Auto-generated from animations.txt
// DO NOT EDIT THIS FILE MANUALLY
// Run: pnpm animations:generate

#ifndef ANIMATIONS_H
#define ANIMATIONS_H

#include <Arduino.h>

// Number of animations
const uint8_t NUM_ANIMATIONS = ${animations.length};

// Palettes: ${animations.length} animations × 24 bytes (8 RGB colors)
const uint8_t PALETTES[${animations.length}][24] PROGMEM = {
${animations
  .map(
    (anim, i) => `  { ${generateByteArray(anim.palette)} }${i < animations.length - 1 ? ',' : ''} // Animation ${i + 1}`
  )
  .join('\n')}
};

// Frames: ${animations.length} animations × 512 bytes (8 frames × 64 pixels)
const uint8_t FRAMES[${animations.length}][512] PROGMEM = {
${animations
  .map(
    (anim, i) => `  { ${generateByteArray(anim.frames)} }${i < animations.length - 1 ? ',' : ''} // Animation ${i + 1}`
  )
  .join('\n')}
};

#endif // ANIMATIONS_H
`

  // Write output file
  try {
    writeFileSync(OUTPUT_FILE, header, 'utf-8')
    console.log(`✓ Successfully generated ${OUTPUT_FILE}`)
    console.log(
      `  Memory usage: ${animations.length} × 536 bytes = ${animations.length * 536} bytes (~${((animations.length * 536) / 1024).toFixed(1)} KB)`
    )
  } catch (error) {
    console.error(`Error writing ${OUTPUT_FILE}:`, error)
    process.exit(1)
  }
}

main()
